<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\OAuth2\Client\Provider\PrestaShop' shared service.

return $this->services['PrestaShop\\OAuth2\\Client\\Provider\\PrestaShop'] = \PrestaShop\Module\PsAccounts\Provider\OAuth2\Oauth2ClientShopProvider::create();
