<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\Module\Mbo\Api\Handler\ErrorHandler\ErrorHandler' shared service.

return $this->services['PrestaShop\\Module\\Mbo\\Api\\Handler\\ErrorHandler\\ErrorHandler'] = new \PrestaShop\Module\Mbo\Api\Handler\ErrorHandler\ErrorHandler(($this->services['ps_mbo'] ?? $this->load('getPsMboService.php')), ($this->services['PrestaShop\\Module\\Mbo\\Api\\Config\\Env'] ?? ($this->services['PrestaShop\\Module\\Mbo\\Api\\Config\\Env'] = new \PrestaShop\Module\Mbo\Api\Config\Env())), ($this->services['logger'] ?? $this->getLoggerService()));
