<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8Hw1iuW\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8Hw1iuW/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8Hw1iuW.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\Container8Hw1iuW\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \Container8Hw1iuW\appAppKernelDevDebugContainer([
    'container.build_hash' => '8Hw1iuW',
    'container.build_id' => '71b332e0',
    'container.build_time' => 1681839674,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8Hw1iuW');
