<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFBx9Gqc\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFBx9Gqc/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFBx9Gqc.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFBx9Gqc\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerFBx9Gqc\appAppKernelDevDebugContainer([
    'container.build_hash' => 'FBx9Gqc',
    'container.build_id' => 'dd3e301b',
    'container.build_time' => 1682441426,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFBx9Gqc');
